#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# short stuff
alias ls='ls --color=auto'
alias pl='puppet-lint --no-80chars-check'
alias yl='/home/bjanssens/.gem/ruby/2.3.0/bin/yaml-lint'
alias l='ls'
alias vn='vagrant destroy -f && vagrant up'
alias vu='vagrant up'
alias vd='vagrant destroy -f'
alias vs='vagrant ssh'
alias vp='vagrant provision'
alias grep='grep --color'

# work tunnels
# internal
alias zimbra-admin-tunnel='ssh -NL 7071:localhost:7071 zimbra.internal'
# viaa
alias vCenter-tunnel-viaa='ssh -N -L 9443:10.9.120.6:9443 leo.inuits.eu'
alias vCenter-console-tunnel-viaa='ssh -N -L 7343:10.9.120.6:7343 leo.inuits.eu'
alias Vcenter-tunnel-digi='sshuttle -r leo.inuits.eu  172.16.0.0/16 10.0.64.0/19 10.0.128.0/19 10.0.32.0/19 172.18.0.0/16 10.9.56.0/24 10.9.160.0/19 172.20.128.0/24 172.20.1.0/24'
# transics
alias cw-xmap-tunnel='ssh -NL 50010:10.10.20.4:50010 inuits@transics-duliut01'
alias mytransics-tunnel-foreman='echo "https://tralsvr097.transicssun.dbn:8443" && ssh -NL 8443:localhost:443 tra-central_001'
alias mytransics-tunnel='sudo vpnc /home/bjanssens/Inuits/Customers/Transics/myTransics/VPN_config/vpnc_transics_config.conf'
alias mytransics-tunnel-stop="sudo kill $( ps aux | grep vpnc | grep -v grep | awk '{ print $2 }' )"
alias pamela-transics='while true; do /home/bjanssens/Inuits/Customers/Pamela/pamela-personal.sh -i wlp3s0 -l Transics | logger; sleep 1200; done &'
alias freeinternet-transics='sshuttle --dns -vvr bjanssens@proxy.inuits.eu:443 0.0.0.0/0 -x 172.16.0.0/24 -x 172.16.123.0/24 -x 10.230.8.0/24 -x 10.231.8.0/24 -x 10.231.3.0/24 -x 10.230.8.0/24 -x 10.230.3.0/24 -x 10.208.6.0/24 -x 10.10.0.0/8 -D --pidfile /tmp/sshuttletransics.pid'
alias freeinternet-transics-stop='kill $( cat /tmp/sshuttletransics.pid )'
# thomascook
alias pamela-thomascook='while true; do /home/bjanssens/Inuits/Customers/Pamela/pamela-personal.sh -i wlp3s0 -l Thomas-Cook | logger; sleep 1200; done &'
alias freeinternet-thomascook='sshuttle --dns -vvr bjanssens@proxy.inuits.eu:443 -x 10.0.0.0/8 -x 57.57.0.0/24 -x 57.57.1.0/24 -x 57.57.10.0/24 -x 57.57.37.0/24 0.0.0.0/0 -D --pidfile /tmp/sshuttlethomascook.pid'
alias freeinternet-thomascook-stop='kill $( cat /tmp/sshuttlethomascook.pid )'
alias thomascook-o-drive='sudo mount -t cifs //10.15.2.200/Belgium/IT /home/bjanssens/Inuits/Customers/ThomasCook/o-drive -o user=T1088240,gid=1000,uid=1000'
alias freeinternet-over-vps='sshuttle --dns -vvr bjanssens@vps.bbqnetwork.be:2200 0.0.0.0/0 -x 10.230.8.0/24 -x 10.231.8.0/24 -x 10.231.3.0/24 -x 10.230.8.0/24 -x 10.230.3.0/24 -x 10.208.6.0/24 -D --pidfile /tmp/sshuttlevps.pid'
alias freeinternet-over-vps-stop='kill $( cat /tmp/sshuttlevps.pid )'
#alias parse-BE-inventory='xlsx2csv /home/bjanssens/Inuits/Customers/ThomasCook/BE-ServerInventory.xlsx -s 2 -d '|' | sed 's/|*$//g' | cut -d '|' -f 1,3,6,8,9,10,12,13,14 > /home/bjanssens/Inuits/Customers/ThomasCook/BE-serverinventory.txt'
# mundev
alias mundev-tunnel-rabbit01='echo "localhost:8082" && ssh -NL 8082:localhost:15672 rabbit01.mundev'
alias mundev-tunnel-rabbit02='echo "localhost:8083" && ssh -NL 8083:localhost:15672 rabbit02.mundev'
alias mundev-tunnel-storm='echo "localhost:8084" && ssh -NL 8084:localhost:8080 app01.mundev'
# lpa
alias lpa-tunnel-icinga='echo "hilde-icinga01.lpa-mgmt.mundosalsa.eu:8080" && ssh -NL 8080:localhost:80 hilde-icinga01.lpamgmt'
alias lpa-tunnel-foreman='echo "localhost:8081" && ssh -NL 8081:localhost:80 hilde-mgmt01.lpamgmt'
alias lpa-tunnel-graphite='echo "localhost:8085" && ssh -NL 8085:localhost:80 hilde-graphite01.lpamgmt'
alias lpa-tunnel-elk='echo "hilde-elk01.lpa-mgmt.mundosalsa.eu:8086" && ssh -NL 8086:localhost:5601 hilde-elk01.lpamgmt'
alias lpa-tunnel-rabbit01='echo "localhost:8082" && ssh -NL 8082:localhost:15672 rabbit01.lpauat'
alias lpa-tunnel-rabbit02='echo "localhost:8083" && ssh -NL 8083:localhost:15672 rabbit02.lpauat'
alias lpa-tunnel-storm='echo "localhost:8084" && ssh -NL 8084:localhost:8080 app01.lpauat'

# handy stuff
alias removespaces='for file in *; do mv "$file" `echo $file | tr " " "_"` ; done'
alias guall='git submodule foreach git checkout master && git submodule foreach git pull --rebase'
alias gpull='git pull --rebase && git submodule --quiet sync && git submodule update --init'
alias network='echo $1 | sudo wpa_cli'
alias git-repo-list="find . -type d -name '*.git' -exec bash -c 'cd $1; git remote -v' - {} \;"

# funny stuff
alias mischief_managed='poweroff'
alias exterminate='rm -rf'
alias ranquot='pchs.co 17'
alias fuck='echo ; echo " (╯°□°）╯︵$(echo "$@"|toilet -f term -F rotate)"; echo'
alias 5pm="/home/bjanssens/Inuits/Scripts/5pm/5pm_again"
alias trafficcli="/home/bjanssens/Inuits/Scripts/Trafficcli/get_traffic_cli"

# Home stuffz
alias update_songs='youtube-dl -x --audio-quality 0 --no-check-certificate --yes-playlist https://www.youtube.com/playlist?list=PLudUzhDi2qezr965RTOqXxYjewnUwmNbh --extract-audio --audio-format mp3 -i'
alias cvlc='cvlc --play-and-exit'
alias vps-tunnel-80='echo "localhost:8080" && ssh -NL 8080:localhost:80 vps'
alias home-tunnel-plex='echo "http://localhost:8080/web/index.html" && ssh -NL 8080:pineapple.internal.bbqnetwork.be:32400 bartjanssens92public@bartjanssens92.duckdns.org -p 22222'
alias home-tunnel-gitlab='ssh -NL 8080:10.10.100.22:80 bartjanssens92public@bartjanssens92.duckdns.org -p 22222'
alias home-tunnel-gitlab2='ssh -NL 8090:10.10.100.25:8080 bartjanssens92public@bartjanssens92.duckdns.org -p 22222'
alias home-tunnel-trans='ssh -NL 8080:10.10.0.251:9091 bartjanssens92public@bartjanssens92.duckdns.org -p 22222'
alias home-tunnel-openwrt='ssh -NL 8080:10.10.0.10:80 bartjanssens92public@bartjanssens92.duckdns.org -p 22222'
alias home-wakeup-ananas2='wol -i 10.10.0.150 d8:cb:8a:c1:d2:bc'
alias home-tunnel-grafana='echo localhost:8081 && ssh -NL 8081:localhost:3000 web01.bbq'
alias home-tunnel-transmission='echo localhost:8081 && ssh -NL 8081:localhost:80 web01.bbq'
alias home-tunnel-influx='echo localhost:8082 && ssh -NL 8082:localhost:8083 web01.bbq'
alias home-tunnel-influx-backend='echo localhost:8086 && ssh -NL 8086:localhost:8086 web01.bbq'
alias home-tunnel-web01='ssh -NL 8080:web01.internal.bbqnetwork.be:80 bartjanssens92public@bartjanssens92.duckdns.org -p 22222'

PATH=$PATH:/home/bjanssens/.gem/ruby/2.2.0/bin

source /home/bjanssens/Inuits/Scripts/bashprompt/source_me

ATLAS_TOKEN=test; export ATLAS_TOKEN
export EDITOR="vim"
VERSION=1; export VERSION
PATH="/home/bjanssens/perl5/bin${PATH+:}${PATH}"; export PATH;
#PERL5LIB="/home/bjanssens/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
#PERL_LOCAL_LIB_ROOT="/home/bjanssens/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
#PERL_MB_OPT="--install_base \"/home/bjanssens/perl5\""; export PERL_MB_OPT;
#PERL_MM_OPT="INSTALL_BASE=/home/bjanssens/perl5"; export PERL_MM_OPT;
